### PR TITLE
Fix modifying of reserved strings

### PR DESCRIPTION
**Pull request by dusan-dragon**
Changed `isReservedString` from private to public on  `StringLiteralObfuscatingReplacer` and added check for reserved strings before calling replace.

I do not fully understand what the StringLiteralObfuscatingReplacer is doing (did not spend that much time in the code) but it seems it will modify strings in the code even if they are included in `reservedStrings` options.

I am creating this PR because we want to use this library in react-native project but when this is modifying reserver strings it will crash our application it wont even start. With this "fix" it works.

Please take a look, it is kind of modifying the output produced by this library, but only 1 test was failing so not sure what impact it can have. Thank you

### CODE REVIEW

**Comment by zamotkin** [comment]
@dusan-dragon thanks for commit! Could you attach an example of code or (better) a test case that works only with your fix?

**Comment by sanex3339** [comment]
Current output on obfuscator.io is
```
const foo='foo\x20baz';
```

**Comment by dusan-dragon** [comment]
Added test which fails on master but passes on this branch

**Comment by dusan-dragon** [comment]
@zamotkin I will try but not sure If I will be able to create such an example as the current obfuscated code is quite complicated and we use more general regex for reserved strings as narrowing down what exactly is the issue is taking too much time

**Comment by zamotkin** [comment]
@dusan-dragon sorry, I can't understand what issue you are trying to solve, I need more details.

**Comment by dusan-dragon** [comment]
I do not know what is exactly the issue but my obfuscated code will not run without this in react native.
So far I narrowed down that there is something wrong if strings which starts with non alphanumeric characters get transformed with this function without my modification,  I know that because I use:
`"reservedStrings": ["^[^a-zA-Z0-9].*$"],` - if I modify that regex to match only strings starting with alphanumerical characters then even this PR does not help...

**Comment by sanex3339** [comment]
Thank you for the PR. I'll reimplement this fix in slightly different way, to work with other literal transformers, so, i'll close this PR in favor of my pr

**Pull request closed without merging**
