### PR TITLE
fix: dynamic import

### PR DESCRIPTION
**Pull request by sxzz**
fix `import('foo')` will be transformed.

### CODE REVIEW

**Comment by sanex3339** [comment]
Hello! The test is failing. Can you fix it?

**Comment by sanex3339** [comment]
Thank you for the PR.
I will slightly update it, also I'm going to rename `ignoreRequireImports` option to `ignoreImports`, so it is a breaking change
Because of that, I'm going to rename `rotateStringArray` => `stringArrayRotate` and `shuffleStringArray` => `stringArrayShuffle`.

I will release it as `3.0.0`

**Comment by sxzz** [comment]
OK, thank you very much. I haven't had time to handle this problem recently.

**Comment by sanex3339** [comment]
Released as `3.0.0`

**Pull request merged**
