### PR TITLE
Bump class-validator from 0.13.2 to 0.14.0

### PR DESCRIPTION
**Pull request by billsykes**
Bumps [class-validator](https://github.com/typestack/class-validator) from 0.13.2 to 0.14.0.
   - [Release notes](https://github.com/typestack/class-validator/releases)
   - [Changelog](https://github.com/typestack/class-validator/blob/develop/CHANGELOG.md)
   - [Commits](https://github.com/typestack/class-validator/compare/v0.13.2...v0.14.0)

   ---
   updated-dependencies:
   - dependency-name: class-validator dependency-type: direct:production ...

### CODE REVIEW

**Comment by billsykes** [comment]
This is to resolve issue #1139. It also fixes the broken test in the similar PR #1140

**Comment by adarshmadrecha** [comment]
Updating to v0.14.0 also fixes the security issue
Ref: https://github.com/advisories/GHSA-fj58-h2fr-3pp2

**Comment by kitsune7** [comment]
+1 on this. The security issue shows up as "critical" in `npm audit`.

**Review by sanex3339 — APPROVED** [review]

**Comment by sanex3339** [comment]
Released

**Pull request merged**
