### PR TITLE
Date lock WIP

### PR DESCRIPTION
**Pull request by sanex3339**

### CODE REVIEW

**Comment by sanex3339** [comment]
Easy, bot

**Comment by sanex3339** [comment]
Easy, bot

**Comment by sanex3339** [comment]
Easy, bot

**Comment by sanex3339** [comment]
Easy bot

**Comment by sanex3339** [comment]
Easy, bot

**Comment by Andrews54757** [comment]
@sanex3339 About the datelock, I suggest against relying on the JavaScript Date methods. This is because the time returned can be manipulated by the user changing the time on their machines. Please look at this:

https://stackoverflow.com/questions/52031772/date-getutcdate-returns-different-results-in-different-timezones-javascript/52032817#52032817

**Comment by Extarys** [comment]
@Andrews54757 I guess it would be slightly better than nothing for those who just want a quick way to lock scripts. It would discourage some users.

**Comment by Andrews54757** [comment]
@sanex3339 @Extarys Should I take a stab and try to do this? With server-based timestamps too...

**Comment by Extarys** [comment]
@Extarys Well if you have time to do it it would be awesome but I personally don't need this right now. It's as you wish. Server-side should adhere to the [KISS](https://en.wikipedia.org/wiki/KISS_principle) principle so it's easy to implement no matter the language.

Maybe just ping a page that only return the timestamp for testing. ( `+Date.now()` )
The user should be able to send custom parameters, for version control or identification.

**Pull request closed without merging**
