### PR TITLE
Simple update to readme.md for "stringArrayEncoding"

### PR DESCRIPTION
**Pull request by alex-drocks**
Removed the wrapping [ ] around the example settings of stringArrayEncoding. When running the obfuscator, it warns that stringArrayEncoding should be a string in the case of "base64" and does not accept ["base64"]

### CODE REVIEW

**Comment by sanex3339** [comment]
What obfuscator version did you used?
The current obfuscator version accepts an array.

**Comment by alex-drocks** [comment]
it fails with latest version 2.9.4 installed

With configs like this (focus on the stringArrayEncoding: ['base64']):
```Javascript
const OBFUSCATOR_OPTS = {
    // See all options on https://obfuscator.io/
    compact: true,
    controlFlowFlattening: false, //!!breaks some windows!! slows down the app by 25%-50%
    controlFlowFlatteningThreshold: 0, //0-1
    deadCodeInjection: false,
    debugProtection: !isDev, //should be true in production builds
    debugProtectionInterval: !isDev, //should be true in production builds
    disableConsoleOutput: !isDev, //should be true in production builds
    identifierNamesGenerator: 'dictionary',
    identifiersDictionary: (function generateIdentifiersDictionary() {
        const dictionary = [];
        [...'abcdefghijklmnopqrstuvwxyz'].forEach(letter => {
            // Use alphabet letters as unique prefix to avoid duplicates
            // and remove non-word chars from the uuid.
            // (longer strings make the obfuscation veery hard understand but code gets slower)
            dictionary.push(
                letter + `${uuidv4()}${uuidv4()}`.replace(/\W+/g, '')
                //==> "a" + "adwercshgreweoiasdfiasiywrwtsd"
            );
        });
        return dictionary;
    })(),
    log: false,
    renameGlobals: true,
    renameProperties: false, //!!!breaks app when true
    rotateStringArray: true,
    seed: 0, //randomize names each time
    selfDefending: !isDev, //should be true in production builds
    shuffleStringArray: true,
    simplify: true,
    sourceMap: false,
    splitStrings: true,
    splitStringsChunkLength: 10,
    stringArray: true,
    stringArrayEncoding: ['base64'],
    stringArrayIndexShift: true,
    stringArrayWrappersCount: 1,
    stringArrayWrappersChainedCalls: true,
    stringArrayWrappersParametersMaxCount: 2,
    stringArrayWrappersType: 'variable',
    stringArrayThreshold: 0.75,
    target: 'node',
    transformObjectKeys: true,
};```

> C:\Users\Alex\Desktop\local-dev-tests\fd-app\node_modules\gulp-javascript-obfuscator\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\options\Options.ts:36
            throw new ReferenceError(`Validation failed. errors:\n${ValidationErrorsFormatter_1.ValidationErrorsFormatter.format(errors)}`);
                  ^
ReferenceError: Validation failed. errors:
`stringArrayEncoding` errors:
    - stringArrayEncoding must be one of the following values: true,false,base64,rc4

    at new o (C:\Users\Alex\Desktop\local-dev-tests\fd-app\node_modules\gulp-javascript-obfuscator\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\options\Options.ts:36:19)
    at _createInstance (C:\Users\Alex\Desktop\local-dev-tests\fd-app\node_modules\inversify\lib\resolution\instantiation.js:21:12)
    at Object.resolveInstance (C:\Users\Alex\Desktop\local-dev-tests\fd-app\node_modules\inversify\lib\resolution\instantiation.js:41:18)
    at C:\Users\Alex\Desktop\local-dev-tests\fd-app\node_modules\inversify\lib\resolution\resolver.js:72:42
    at Array.map (<anonymous>)
    at Object.resolveInstance (C:\Users\Alex\Desktop\local-dev-tests\fd-app\node_modules\inversify\lib\resolution\instantiation.js:40:67)
    at C:\Users\Alex\Desktop\local-dev-tests\fd-app\node_modules\inversify\lib\resolution\resolver.js:72:42
    at Array.map (<anonymous>)
    at Object.resolveInstance (C:\Users\Alex\Desktop\local-dev-tests\fd-app\node_modules\inversify\lib\resolution\instantiation.js:40:67)
    at C:\Users\Alex\Desktop\local-dev-tests\fd-app\node_modules\inversify\lib\resolution\resolver.js:72:42
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! finance-d-app@0.9.1 build-for-testing: `gulp setDevMode && gulp bundle && gulp inline && npm run package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the finance-d-app@0.9.1 build-for-testing script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex\AppData\Roaming\npm-cache\_logs\2020-12-09T13_28_24_288Z-debug.log

**Comment by sanex3339** [comment]
The error message is not from the latest version of obfuscator. So, seems gulp-javascript-obfuscator is using an older version in your case.

**Comment by alex-drocks** [comment]
Ok thanks, feel free to cancel the pull request.

**Pull request closed without merging**
