### PR TITLE
New `obfuscateMultiple` method

### PR DESCRIPTION
**Pull request by sanex3339**

### CODE REVIEW

**Comment by Ben-Mack** [comment]
Does this ensure the same variable name is mangled to the same name across files? (i.e all variable named `foo` will be mangled to `x` in all files)
Or the mangled names will be different in each file just like calling `obfuscate` separately?

**Comment by sanex3339** [comment]
Hmm. Looks like i forgot about it. Currently variable names will be the same. WIll fix it.

**Comment by Ben-Mack** [comment]
Please consider the case where variable `foo` is declared in one file, and the other files has references to that variable (which mean it should be mangled to the same name).

**Comment by sanex3339** [comment]
@Ben-Mack for that case you shouldn't use `renameGlobals` option

**Comment by Ben-Mack** [comment]
So basically `obfuscateMultiple` will provide the same result as calling `obfuscate` on each file? 
Does it have any difference in functionality?

**Comment by sanex3339** [comment]
After `identifiersPrefix` fix it will just as calling obfuscate on each file, but with different identifiers prefix.

**Comment by sanex3339** [comment]
Currently `obfuscateMultiple` is simple:
```ts
public static obfuscateMultiple <TSourceCodesObject extends TObject<string>> (
        sourceCodesObject: TSourceCodesObject,
        inputOptions: TInputOptions = {}
    ): TObfuscationResultsObject<TSourceCodesObject> {
        if (typeof sourceCodesObject !== 'object') {
            throw new Error('Source codes object should be a plain object');
        }

        return Object
            .keys(sourceCodesObject)
            .reduce(
                (
                    acc: TObfuscationResultsObject<TSourceCodesObject>,
                    sourceCodeIdentifier: keyof TSourceCodesObject,
                    index: number
                ) => {
                    const identifiersPrefix: string = Utils.getIdentifiersPrefixForMultipleSources(
                        inputOptions.identifiersPrefix,
                        index
                    );

                    const sourceCode: string = sourceCodesObject[sourceCodeIdentifier];
                    const sourceCodeOptions: TInputOptions = {
                        ...inputOptions,
                        identifiersPrefix
                    };

                    return {
                        ...acc,
                        [sourceCodeIdentifier]: JavaScriptObfuscatorFacade.obfuscate(sourceCode, sourceCodeOptions)
                    };
                },
                <TObfuscationResultsObject<TSourceCodesObject>>{}
            );
    }
```

**Comment by Ben-Mack** [comment]
`javascript-obfuscator` should has something like an `obfuscatedMap` that records the mapping between original and mangled names. 
It will opening the possibility to obfuscate the library code (which result in much more obscured code).
The case will be like I obfuscate the library code first, then pass its `obfuscatedMap` to obfuscate other files using the library to ensure it refers to correct mangled names.

**Comment by sanex3339** [comment]
Usually, all library identifiers are exported via `export foo` or `export {foo};`
These identifiers won't be obfuscated.
Global identifiers will be obfuscated only if `renameGlobals` option is enabled. 
As described in the readme, `vendors` obfuscation is not a good thing because of performance slowdown, so `obfuscatedMap` not in the nearest plans.

**Comment by sanex3339** [comment]
Released `0.27.2` with `identifiersPrefix` fix

**Comment by reeezzz1** [comment]
Hello, first of all congratulations on a great library! :)
We use it in company I work for our projects and it works great!
What @Ben-Mack suggests about "obfuscatedMap" or other way to have "cross-file" obfuscation would be really good option.
Not because we need to obfuscate external libraries but for two reasons:

1) some of our JS code is in EJS / HTML files. Our idea was to create a script that extracts parts of JS like '<script>...</script>' or 'onclick="..."' from HTML save it temporarly as JS files obfuscate it together with each other and put back to HTML. The problem is that if one part use same variable as the other part it will not be obfuscated with the same name or at all (if it is not defined in that part). So kind of cross-file obfuscation would be a great option and would save a lot of trouble with adding variables to exceptions (and we don't want to leave all globals not obfuscated).

2) we have our own JS files/libraries that are separate files but sometimes have some global variables/functions that are used in other files. (and we don't want to join all our files in one file as we have a lot of different files that are not needed in every place)

There is this kind of option in this solution: https://javascriptobfuscator.com/docs/ReplaceGlobals.aspx
They call it "Cross File Obfuscation".
Would it be possible to implement it?
It would be a great, great improvement and time saver with dealing with exceptions etc.
Again congratulations and thanks for creating a great library and best wishes! :)

**Comment by sanex3339** [comment]
There are many requests for this feature, so will try it in the future.

**Comment by reeezzz1** [comment]
Would be great! :)

**Pull request merged**
