### PR TITLE
Add --config CLI option

### PR DESCRIPTION
**Pull request by psabharwal123**
Add --config CLI option that accepts name of js / json file that contains all config instead of passing everything in CLI

### CODE REVIEW

**Comment by sanex3339** [comment]
Hi! Thank you for PR, i'll check it later today.

**Comment by sanex3339** [comment]
Thank you!

**Comment by psabharwal123** [comment]
np! let me know if you need help with something

**Comment by psabharwal123** [comment]
also when would this make it to npm?

**Comment by sanex3339** [comment]
Beta release - today. Stable release - today or tomorrow.

**Comment by sanex3339** [comment]
Check new `javascript-obfuscator@0.10.0-beta.12`.

Expect stable version later today.

**Comment by psabharwal123** [comment]
thanks, i noticed an issue due to which this doesnt work. Webpack seems to convert  'require(configFileLocation)' in file JavaScriptObfuscatorCLI. ~line 103 to !function(){var e=new Error('Cannot find module "."');throw e.code="MODULE_NOT_FOUND",e}(). I cannot figure out why. Also since this would run in node env only do we need to webpack everything into one file?

**Pull request merged**
