### PR TITLE
Fix domainLock in SVG - issue #273

### PR DESCRIPTION
**Pull request by srguiwiz**
Also have verified it really fixes the issue.

### CODE REVIEW

**Comment by sanex3339** [comment]
Awesome. Will merge it later today.

**Comment by sanex3339** [comment]
Add tests please here:
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/test/functional-tests/templates/domain-lock-nodes/DomainLockNodeTemplate.spec.ts

**Comment by srguiwiz** [comment]
The improved code in tests better reflects browsers.

**Comment by sanex3339** [comment]
Thank you!

**Pull request merged**
