### PR TITLE
Use the dictionary as the name of the identifiers

### PR DESCRIPTION
**Pull request by adiantek**
I added option to obfuscate code using dictionary and it looks like (based on three words: qwertyuiop, asdfghjkl, zxcvbnm and prefix obfuscatorio_):
image

source, before this obfuscation:

```
function helloWorld() {
	console.log("Hello world!");
}
setInterval(helloWorld, 500);

```

### CODE REVIEW

**Comment by phongbuigk1996** [comment]
zxcvbnm25101996@yahoo.com

**Comment by sanex3339** [comment]
Hi. Are you interested in an update of this PR? If not, I'll update it by myself

**Comment by adiantek** [comment]
You can update yourself if you want

**Comment by sanex3339** [comment]
Thank you! I updated and refactored your changes in my PR
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/462

Closed.

**Pull request closed without merging**
