### PR TITLE
Identifier names generator block scope

### PR DESCRIPTION
**Pull request by sanex3339**

### CODE REVIEW

**Comment by sanex3339** [comment]
Easy, bot

**Comment by Extarys** [comment]
Does this implement the idea I suggested [here](https://github.com/javascript-obfuscator/javascript-obfuscator/issues/371)? :heart:

**Comment by zamotkin** [comment]
@sanex3339 All test are green now, but I'm not sure that this solution is perfect.

**Comment by sanex3339** [comment]
I'll check this in an hour.
I tested this feature on angular2 bundle, so will test it in the current state

**Comment by sanex3339** [comment]
Huge obfuscation performance drop: from 7 seconds to 270 seconds.
And still errors on angular2 bundle obfuscation with duplicate parameters

```
for (var aN = 0x0; aN < aL['length']; aN++) {
                    var bx = aL[aN];
                    aj(aM, bx, function (bx, by, bx) {
                        return function (bA, bB) {
                            return Zone[b('0xc8')][b('0x877')](bx, aM, bB, bx); // <- here
                        };
                    });
                }
```

**Comment by sanex3339** [comment]
I tested obfuscator on this angular2 bundle:
https://github.com/sanex3339/laravel-5-angular-2-example

```
javascript-obfuscator public/js/vendor.d96bca529f0fd4b40c83.js --compact false --identifier-names-generator mangled --transform-object-keys true --log true
```

**Comment by zamotkin** [comment]
Yes, I see. I think we need a different approach, maybe without eslint-scope, it helps a bit.

**Comment by sanex3339** [comment]
1

**Comment by sanex3339** [comment]
Closed in favor of new PR
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/555

**Pull request closed without merging**
